// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	client.proto
	service.proto

It has these top-level messages:
	GetRequest
	PutRequest
	DelRequest
	ClientReply
	KVPair
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	Identity string `protobuf:"bytes,1,opt,name=identity" json:"identity,omitempty"`
	Key      string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type PutRequest struct {
	Identity string `protobuf:"bytes,1,opt,name=identity" json:"identity,omitempty"`
	Key      string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value    []byte `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PutRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *PutRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type DelRequest struct {
	Identity string `protobuf:"bytes,1,opt,name=identity" json:"identity,omitempty"`
	Key      string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Force    bool   `protobuf:"varint,3,opt,name=force" json:"force,omitempty"`
}

func (m *DelRequest) Reset()                    { *m = DelRequest{} }
func (m *DelRequest) String() string            { return proto.CompactTextString(m) }
func (*DelRequest) ProtoMessage()               {}
func (*DelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DelRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *DelRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DelRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type ClientReply struct {
	Success  bool    `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Redirect string  `protobuf:"bytes,2,opt,name=redirect" json:"redirect,omitempty"`
	Error    string  `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	Pair     *KVPair `protobuf:"bytes,7,opt,name=pair" json:"pair,omitempty"`
}

func (m *ClientReply) Reset()                    { *m = ClientReply{} }
func (m *ClientReply) String() string            { return proto.CompactTextString(m) }
func (*ClientReply) ProtoMessage()               {}
func (*ClientReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ClientReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ClientReply) GetRedirect() string {
	if m != nil {
		return m.Redirect
	}
	return ""
}

func (m *ClientReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ClientReply) GetPair() *KVPair {
	if m != nil {
		return m.Pair
	}
	return nil
}

// Used for transmitting key/value pairs on the network
type KVPair struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *KVPair) Reset()                    { *m = KVPair{} }
func (m *KVPair) String() string            { return proto.CompactTextString(m) }
func (*KVPair) ProtoMessage()               {}
func (*KVPair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *KVPair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KVPair) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "pb.GetRequest")
	proto.RegisterType((*PutRequest)(nil), "pb.PutRequest")
	proto.RegisterType((*DelRequest)(nil), "pb.DelRequest")
	proto.RegisterType((*ClientReply)(nil), "pb.ClientReply")
	proto.RegisterType((*KVPair)(nil), "pb.KVPair")
}

func init() { proto.RegisterFile("client.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x31, 0x4b, 0xc4, 0x30,
	0x14, 0x80, 0x49, 0x4f, 0xef, 0x7a, 0xef, 0x6e, 0x90, 0xe0, 0x10, 0x1c, 0xa4, 0x74, 0xea, 0x54,
	0x44, 0x37, 0x57, 0x05, 0x07, 0x97, 0xf2, 0x06, 0xf7, 0x36, 0xf7, 0x84, 0x60, 0xb9, 0xc6, 0xd7,
	0x44, 0xc8, 0xbf, 0x97, 0x24, 0xde, 0xe1, 0x70, 0x53, 0xb7, 0x7c, 0x0f, 0xf2, 0x25, 0x1f, 0x0f,
	0xf6, 0x7a, 0x34, 0x74, 0x74, 0xad, 0xe5, 0xc9, 0x4d, 0xb2, 0xb0, 0x43, 0xfd, 0x0c, 0xf0, 0x46,
	0x0e, 0xe9, 0xdb, 0xd3, 0xec, 0xe4, 0x1d, 0x94, 0xe6, 0x40, 0x47, 0x67, 0x5c, 0x50, 0xa2, 0x12,
	0xcd, 0x16, 0xcf, 0x2c, 0x6f, 0x60, 0xf5, 0x45, 0x41, 0x15, 0x69, 0x1c, 0x8f, 0x75, 0x07, 0xd0,
	0xf9, 0x65, 0x77, 0xe5, 0x2d, 0x5c, 0xff, 0xf4, 0xa3, 0x27, 0xb5, 0xa9, 0x44, 0xb3, 0xc7, 0x0c,
	0xd1, 0xf8, 0x4a, 0xe3, 0x62, 0xe3, 0xe7, 0xc4, 0x9a, 0xd4, 0xaa, 0x12, 0x4d, 0x89, 0x19, 0xea,
	0x00, 0xbb, 0x97, 0xd4, 0x8c, 0x64, 0xc7, 0x20, 0x15, 0x6c, 0x66, 0xaf, 0x35, 0xcd, 0x73, 0x32,
	0x96, 0x78, 0xc2, 0xf8, 0x18, 0xd3, 0xc1, 0x30, 0x69, 0xf7, 0x67, 0x3d, 0x73, 0x54, 0x13, 0xf3,
	0xc4, 0x49, 0xbd, 0xc5, 0x0c, 0xf2, 0x1e, 0xae, 0x6c, 0x6f, 0x38, 0x15, 0xec, 0x1e, 0xa1, 0xb5,
	0x43, 0xfb, 0xfe, 0xd1, 0xf5, 0x86, 0x31, 0xcd, 0xeb, 0x07, 0x58, 0x67, 0x3e, 0x7d, 0x56, 0x5c,
	0xc8, 0x2f, 0xfe, 0xe5, 0x0f, 0xeb, 0xb4, 0x97, 0xa7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x77,
	0xc2, 0x32, 0xde, 0xa7, 0x01, 0x00, 0x00,
}
